### ISSUE TITLE
Copy local gems specified with path in Gemfile

### ISSUE THREAD

**Issue by Antsiscool** [rubys/dockerfile-rails#18]
We have a couple of generated gems that are in the same repo as our application.

Bundle install fails if they haven't been copied to docker image.

Would it be possible to look through the Gemfile/ Gemfile.lock for all gems specified with with a path and copy them before running bundle install

**Comment by rubys** [comment]
> We have a couple of generated gems that are in the same repo as our application.

Would it be possible to see an example?

> Would it be possible to look through the Gemfile/ Gemfile.lock for all gems specified with with a path and copy them before running bundle install

If these gems are in a subdirectory of the main application they will already be copied, but their absolute paths on the resulting container will be different than on your development machine.

If these gems are outside of the directory of the main application, they won't be copied to the build machine at all.

If I can see an example (either an existing project on GitHub or a small test case) I can explore getting it to work.  I would also welcome pull requests.

**Comment by rubys** [comment]
Please reopen once you have an example or more information.  I definitely feel this is doable, but I don't want to guess.
