### ISSUE TITLE
redis detection should check for `redis` gem instead of `sidekiq`

### ISSUE THREAD

**Issue by olbrich** [rubys/dockerfile-rails#23]
https://github.com/rubys/dockerfile-rails/blob/718a4ad457d4a1330cc39788bdf55a07531adbbd/lib/generators/dockerfile_generator.rb#L300-L302

It seems like this function should be checking for the presence of `redis` or possibly `redis-client` in the bundle instead of `sidekiq`. I think

**Comment by rubys** [comment]
If you have redis installed on your computer, 'rails new` will automatically add redis to your Gemfile, so having it in your Gemfile is not a reliable indicator of whether or not your application actually uses redis.

`using_redis?` is currently used for two things: actually adding the redis gem if it is going to be needed in production, and adding a redis container to docker-compose.yml.  Neither of these actions should be done unless there is an indication that redis is actually being used and not merely included in the Gemfile.

**Comment by rubys** [comment]
Comments added to source.  Feel free to reopen if you don't think this is sufficient.

**Comment by olbrich** [comment]
Thanks for clarifying!
