### ISSUE TITLE
Add IP binding on rails server?

### ISSUE THREAD

**Issue by olbrich** [rubys/dockerfile-rails#28]
I'm not entirely sure this is necessary in all cases, but in my experiments, I had to change this line to get my app to work properly.

https://github.com/rubys/dockerfile-rails/blob/95215795f7ab517f716485a841ec166db954835d/lib/generators/dockerfile_generator.rb#L816

to 

```
rails: "./bin/rails server -b 0.0.0.0"
```

**Comment by rubys** [comment]
Can you describe a bit more about how you are deploying?  My only hesitation is that I'm trying to match Rails 7.1's [Dockerfile.tt](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/Dockerfile.tt), and I don't need that change with 'docker run`, 'docker compose up`, or `fly.io`.

Is there anything else unique or notable about your application?  Perhaps you are using an older version of Rails?

**Comment by olbrich** [comment]
I am using Rails 7.0, so not that old. I don't know if there was a recent change in `rails server` that makes the `-b 0.0.0.0` unnecessary.

At the moment I'm still sorting out how to set up and test this, so I've been running the docker container locally and then just configuring a 'staging' environment to connect to local resources.

**Comment by rubys** [comment]
Do these demos work for you: https://github.com/rubys/dockerfile-rails/blob/main/DEMO.md ?

**Comment by olbrich** [comment]
The first one did. I went back and undid my change and it now seems to be working. I must have had an unrelated change that broke things and misinterpreted the fix.
